application_hosts:
  afvalwijzer: fed
  authelia: fed
  containers-backup:
    - fed
    - unas 
  energy-meters: fed
  grafana: fed
  guacamole: fed
  homeconnect-proxy: fed
  inadyn: fed
  influxdb: fed
  memos: fed
  mosquitto: fed
  nginx-proxy-manager: fed
  openhab: fed
  passbolt: fed
  zigbee2mqtt: fed
  rustdesk: unas
  backup-manager:
    - unas
    - vm